### ISSUE TITLE
Determine Docs Hosting

### ISSUE THREAD

**Issue by bbengfort** [trisacrypto/trisa#47]
- [x] What domain? e.g. do we continue to host the official v1beta1 docs at trisatest.net? 
- [x] Do we keep GitHub Pages or continue to use containers?

**Comment by rebeccabilbro** [comment]
After some discussion about i18n and l10n (internationalization and localization), here is our currently thinking:

- for the domain, we'd like to try to get `trisa.dev`, which would allow us to use a multilingual approach where other languages are hosted at, for instance, `trisa.dev/fr`, `trisa.dev/ms`, and `trisa.dev/zh`.
- for the hosting strategy, we'd like to use Github pages, since it seems like we are most likely to net i18n/l10n features there.

**Comment by rebeccabilbro** [comment]
@bbengfort @ayyoitsp ok to mark this as resolved?

**Comment by bbengfort** [comment]
@rebeccabilbro GitHub pages works for me! I've registered trisa.dev for the docs.
